### ISSUE TITLE
Not activating mod

### ISSUE THREAD

**Issue by ninjaguardian** [aternosorg/mclogs-fabric#5]
I use 1.19.2 quilt on modrinth app and when I start minecraft, the mod is not in my mod list or game.

**Comment by JulianVennen** [comment]
Please share your client log

**Comment by ninjaguardian** [comment]
It is an older version of mclogs because they stoped updating 1.19

**Comment by ninjaguardian** [comment]
search for mclogs `[12:06:00] [main/INFO]:
 Loading Minecraft 1.19.2 with Quilt Loader 0.21.0-beta.3
[12:06:00] [main/INFO]:
 Loading mappings: jar:file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/quiltmc/hashed/1.19.2/hashed-1.19.2.jar!/mappings/mappings.tiny
[12:06:00] [main/INFO]:
 Skipping mappings: Missing namespace 'intermediary'
[12:06:00] [main/INFO]:
 Loading mappings: jar:file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar!/mappings/mappings.tiny
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/block_content_registry-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 - Unnecessary dependency range 1.19.2 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.19.2, 2)), since it doesn't affect the result [1.19.1, 2)
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/block_entity-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:16] [Render thread/INFO]:
 [STDERR]: 	JRE: Windows amd64 17.0.8
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/block_extensions-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 - Unnecessary dependency range 1.19.2 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.19.2, 2)), since it doesn't affect the result [1.19.1, 2)
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/crash_info-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/registry-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 - Unnecessary dependency range 1.19.2 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.19.2, 2)), since it doesn't affect the result [1.19.1, 2)
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/networking-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/lifecycle_events-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/resource_loader-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/tags-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 - Unnecessary dependency range 1.19.2 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.19.2, 2)), since it doesn't affect the result [1.19.1, 2)
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/recipe-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:01] [main/WARN]:
 - Deprecated array format for dependencies: see https://github.com/QuiltMC/rfcs/pull/56 for more information.
[12:06:01] [main/WARN]:
 - Unnecessary dependency range 1.19.2 at line 31 column 7 path $.quilt_loader.depends[1].versions[0] (resolves as [1.19.2, 2)), since it doesn't affect the result [1.19.1, 2)
[12:06:01] [main/WARN]:
 Warnings for quilt.mod.json at: '<mods>/qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar!/META-INF/jars/advancement-3.0.0-beta.29+1.19.2.jar!/quilt.mod.json'
[12:06:17] [Render thread/WARN]:
 Assets URL 'quilt.zfs://transformed-mod-minecraft.i0:0/data/.mcassetsroot' uses unexpected schema
[12:06:17] [Render thread/WARN]:
 Assets URL 'quilt.zfs://transformed-mod-minecraft.i0:0/assets/.mcassetsroot' uses unexpected schema
[12:06:16] [Render thread/INFO]:
 [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Local\Temp\lwjglcarte\3.3.1-build-7\jemalloc.dll
[12:06:16] [Render thread/INFO]:
 [STDERR]: 	Module: org.lwjgl.jemalloc
[12:06:33] [Render thread/INFO]:
 [STDERR]: 	opengl32.dll not found in org.lwjgl.librarypath=C:\Users\{COMPUTER_USERNAME}\AppData\Local\Temp\lwjglcarte\3.3.1-build-7
[12:06:16] [Render thread/INFO]:
 [STDERR]: 	Loaded from org.lwjgl.librarypath: C:\Users\{COMPUTER_USERNAME}\AppData\Local\Temp\lwjglcarte\3.3.1-build-7\lwjgl.dll
[12:06:16] [Render thread/INFO]:
 [STDERR]: MemoryUtil allocator: JEmallocAllocator
[12:06:18] [Render thread/INFO]:
 Setting user: {MINECRAFT_USERNAME}
[12:06:16] [Render thread/INFO]:
 [STDERR]: Loading library: jemalloc
[12:06:16] [main/INFO]:
 [Quilt Command] Networking support is enabled
[12:06:16] [Render thread/INFO]:
 [STDERR]: 	Module: org.lwjgl
[12:06:33] [Render thread/INFO]:
 [STDERR]: 	Module: org.lwjgl.opengl
[12:06:16] [Render thread/INFO]:
 [STDERR]: 	JVM: OpenJDK 64-Bit Server VM v17.0.8+7-LTS by Microsoft
[12:06:16] [main/WARN]:
 @Redirect conflict. Skipping #imm_ptl_core:imm_ptl.mixins.json:common.position_sync.MixinServerGamePacketListenerImpl from mod imm_ptl_core->@Redirect::redirectIsInTeleportationState(Lnet/minecraft/class_3222;)Z with priority 900, already redirected by #carpet:carpet.mixins.json:ServerGamePacketListenerImpl_antiCheatDisabledMixin from mod carpet->@Redirect::relaxMoveRestrictions(Lnet/minecraft/class_3222;)Z with priority 1000
|     6 | api                                               | gs_mclo_api                                          | 4.0.1                       | Fabric  | d4c3e124fbaccd10eea63b4cb7f6fe191ea14317 | <mods>\mclogs-fabric-1.4.1-1.19.jar                                                                                                            | /META-INF/jars/api-4.0.1.jar                                                                              |`

**Comment by ninjaguardian** [comment]
[12:08:15] [Render thread/WARN]:
 Warning! Mod gs_mclo_api has a broken icon, loading default icon
 
 showed up but mclogs is still not there
![image](https://github.com/aternosorg/mclogs-fabric/assets/110734253/2684b542-664d-4d3c-81f6-b9dad113c305)

**Comment by ninjaguardian** [comment]
tried to install in different mod set and still wont work

**Comment by JulianVennen** [comment]
It is configured to only run on servers for now.
