### ISSUE TITLE
suggestion client side feature

### ISSUE THREAD

**Issue by Thunderrock424242** [aternosorg/mclogs-fabric#8]
instead of only being needed on the server it would be nice to have a option to uplaod your latest log or client log so you can see what is bugging ingame.

**Comment by RealmKebab** [comment]
i dont think that would be useful, you could just use prism launcher

**Comment by JulianVennen** [comment]
I'm working on this and would love to release it in all versions but unfortunately CurseForge is down right now 😅

**Comment by JulianVennen** [comment]
It should now be available for 1.16-1.20. 1.14/15 do not offer this functionality and are therefore no longer supported. 
1.21 should be there in a few minutes.
